-- UNI-16 reproducible schema baseline (squash of 0000-0011 into the current
-- per-region factory schema). Apply to an EMPTY database to recreate the full
-- production structure:  psql "$DATABASE_URL" -f drizzle/0012_baseline.sql
--
-- Tables/columns/standard indexes are generated by drizzle-kit from
-- src/services/db/schema/*.ts (the makeXxxTable factories, all 3 regions).
-- The trailing *_snapshots_latest_membership_idx partial covering indexes are
-- hand-maintained (drizzle-kit cannot express INCLUDE/partial/DESC); they are
-- carried over verbatim from drizzle/0011_snapshots_latest_membership_idx.sql.
-- Do NOT db:push (DROPs every per-region table). See AGENTS.md > Database migrations.

CREATE TABLE "asia_clan_members" (
	"clan_id" bigint NOT NULL,
	"account_id" bigint NOT NULL,
	"name" text NOT NULL,
	"role" text NOT NULL,
	"role_localized" text NOT NULL,
	"role_rank" integer NOT NULL,
	"days_in_clan" integer NOT NULL,
	"last_battle_time" timestamp with time zone,
	"personal_rating" integer,
	"overall_battles" integer,
	"overall_wins_pct" real,
	"overall_damage_per_battle" real,
	"overall_exp_per_battle" real,
	"overall_frags_per_battle" real,
	"overall_battles_per_day" real,
	"d28_battles" integer,
	"d28_wins_pct" real,
	"d28_damage_per_battle" real,
	"d28_exp_per_battle" real,
	"d28_frags_per_battle" real,
	"d28_battles_per_day" real,
	"refreshed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "asia_clan_members_clan_id_account_id_pk" PRIMARY KEY("clan_id","account_id")
);
--> statement-breakpoint
CREATE TABLE "asia_clan_recent_events" (
	"clan_id" bigint NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"type" text NOT NULL,
	"account_id" bigint NOT NULL,
	"account_name" text NOT NULL,
	"old_role" text,
	"new_role" text,
	"old_rank" integer,
	"new_rank" integer,
	CONSTRAINT "asia_clan_recent_events_clan_id_created_at_type_account_id_pk" PRIMARY KEY("clan_id","created_at","type","account_id")
);
--> statement-breakpoint
CREATE TABLE "asia_clan_refresh_queue" (
	"clan_id" bigint PRIMARY KEY NOT NULL,
	"queued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "asia_clans" (
	"id" bigint PRIMARY KEY NOT NULL,
	"tag" text NOT NULL,
	"tag_lower" text NOT NULL,
	"name" text NOT NULL,
	"color" text NOT NULL,
	"emblem" text NOT NULL,
	"motto" text NOT NULL,
	"description_html" text NOT NULL,
	"members_count" integer NOT NULL,
	"leader_id" bigint NOT NULL,
	"leader_name" text NOT NULL,
	"creator_id" bigint NOT NULL,
	"creator_name" text NOT NULL,
	"created_at_wg" timestamp with time zone NOT NULL,
	"is_disbanded" boolean DEFAULT false NOT NULL,
	"languages" text[] DEFAULT '{}' NOT NULL,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_refreshed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "asia_player_clan_history" (
	"id" serial PRIMARY KEY NOT NULL,
	"account_id" bigint NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"data" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "asia_player_refresh_queue" (
	"account_id" bigint PRIMARY KEY NOT NULL,
	"queued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "asia_player_snapshots" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"taken_at" timestamp with time zone DEFAULT now() NOT NULL,
	"battles" integer NOT NULL,
	"wins" integer NOT NULL,
	"losses" integer NOT NULL,
	"draws" integer NOT NULL,
	"survived_battles" integer NOT NULL,
	"frags" integer NOT NULL,
	"damage_dealt" bigint NOT NULL,
	"damage_received" bigint NOT NULL,
	"xp" bigint NOT NULL,
	"battle_avg_xp" integer NOT NULL,
	"spotted" integer NOT NULL,
	"capture_points" integer NOT NULL,
	"dropped_capture_points" integer NOT NULL,
	"hits" integer NOT NULL,
	"shots" integer NOT NULL,
	"hits_percents" real NOT NULL,
	"global_rating" integer NOT NULL,
	"wtr" integer,
	"clan_id" bigint
);
--> statement-breakpoint
CREATE TABLE "asia_players" (
	"id" serial PRIMARY KEY NOT NULL,
	"account_id" bigint NOT NULL,
	"nickname" text NOT NULL,
	"created_at" timestamp with time zone,
	"last_battle_at" timestamp with time zone,
	"clan_id" bigint,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"wn7" real,
	"wn8" real,
	"wnx" real,
	"wn7_30d" real,
	"wn8_30d" real,
	"wnx_30d" real,
	"battles" integer,
	"battles_30d" integer,
	"null_count" integer DEFAULT 0 NOT NULL,
	"soft_deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "asia_tank_snapshots" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"tank_id" integer NOT NULL,
	"taken_at" timestamp with time zone DEFAULT now() NOT NULL,
	"battles" integer NOT NULL,
	"wins" integer NOT NULL,
	"damage_dealt" bigint NOT NULL,
	"spotted" integer NOT NULL,
	"frags" integer NOT NULL,
	"dropped_capture_points" integer NOT NULL,
	"radio_assisted_damage" bigint NOT NULL,
	"track_assisted_damage" bigint NOT NULL,
	"xp" bigint,
	"mark_of_mastery" integer
);
--> statement-breakpoint
CREATE TABLE "asia_top_clans" (
	"metric" text NOT NULL,
	"rank" integer NOT NULL,
	"clan_id" bigint NOT NULL,
	"tag" text NOT NULL,
	"name" text NOT NULL,
	"color" text NOT NULL,
	"emblem" text,
	"members_count" integer NOT NULL,
	"rated_members_count" integer NOT NULL,
	"avg_wnx" numeric NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "asia_top_clans_metric_rank_pk" PRIMARY KEY("metric","rank")
);
--> statement-breakpoint
CREATE TABLE "asia_top_players" (
	"metric" text NOT NULL,
	"period" text NOT NULL,
	"rank" integer NOT NULL,
	"account_id" bigint NOT NULL,
	"nickname" text NOT NULL,
	"clan_tag" text,
	"clan_color" text,
	"battles" integer NOT NULL,
	"wnx" numeric NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "asia_top_players_metric_period_rank_pk" PRIMARY KEY("metric","period","rank")
);
--> statement-breakpoint
CREATE TABLE "asia_vehicles" (
	"tank_id" integer PRIMARY KEY NOT NULL,
	"tier" integer NOT NULL,
	"type" text NOT NULL,
	"nation" text NOT NULL,
	"name" text NOT NULL,
	"short_name" text NOT NULL,
	"tag" text NOT NULL,
	"is_premium" boolean NOT NULL,
	"is_wheeled" boolean NOT NULL,
	"is_gift" boolean NOT NULL,
	"small_icon" text,
	"contour_icon" text,
	"big_icon" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cron_leader" (
	"id" integer PRIMARY KEY NOT NULL,
	"instance_id" text NOT NULL,
	"acquired_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "cron_leader_singleton" CHECK ("cron_leader"."id" = 1)
);
--> statement-breakpoint
CREATE TABLE "eu_clan_members" (
	"clan_id" bigint NOT NULL,
	"account_id" bigint NOT NULL,
	"name" text NOT NULL,
	"role" text NOT NULL,
	"role_localized" text NOT NULL,
	"role_rank" integer NOT NULL,
	"days_in_clan" integer NOT NULL,
	"last_battle_time" timestamp with time zone,
	"personal_rating" integer,
	"overall_battles" integer,
	"overall_wins_pct" real,
	"overall_damage_per_battle" real,
	"overall_exp_per_battle" real,
	"overall_frags_per_battle" real,
	"overall_battles_per_day" real,
	"d28_battles" integer,
	"d28_wins_pct" real,
	"d28_damage_per_battle" real,
	"d28_exp_per_battle" real,
	"d28_frags_per_battle" real,
	"d28_battles_per_day" real,
	"refreshed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "eu_clan_members_clan_id_account_id_pk" PRIMARY KEY("clan_id","account_id")
);
--> statement-breakpoint
CREATE TABLE "eu_clan_recent_events" (
	"clan_id" bigint NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"type" text NOT NULL,
	"account_id" bigint NOT NULL,
	"account_name" text NOT NULL,
	"old_role" text,
	"new_role" text,
	"old_rank" integer,
	"new_rank" integer,
	CONSTRAINT "eu_clan_recent_events_clan_id_created_at_type_account_id_pk" PRIMARY KEY("clan_id","created_at","type","account_id")
);
--> statement-breakpoint
CREATE TABLE "eu_clan_refresh_queue" (
	"clan_id" bigint PRIMARY KEY NOT NULL,
	"queued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "eu_clans" (
	"id" bigint PRIMARY KEY NOT NULL,
	"tag" text NOT NULL,
	"tag_lower" text NOT NULL,
	"name" text NOT NULL,
	"color" text NOT NULL,
	"emblem" text NOT NULL,
	"motto" text NOT NULL,
	"description_html" text NOT NULL,
	"members_count" integer NOT NULL,
	"leader_id" bigint NOT NULL,
	"leader_name" text NOT NULL,
	"creator_id" bigint NOT NULL,
	"creator_name" text NOT NULL,
	"created_at_wg" timestamp with time zone NOT NULL,
	"is_disbanded" boolean DEFAULT false NOT NULL,
	"languages" text[] DEFAULT '{}' NOT NULL,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_refreshed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "eu_player_clan_history" (
	"id" serial PRIMARY KEY NOT NULL,
	"account_id" bigint NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"data" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "eu_player_refresh_queue" (
	"account_id" bigint PRIMARY KEY NOT NULL,
	"queued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "eu_player_snapshots" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"taken_at" timestamp with time zone DEFAULT now() NOT NULL,
	"battles" integer NOT NULL,
	"wins" integer NOT NULL,
	"losses" integer NOT NULL,
	"draws" integer NOT NULL,
	"survived_battles" integer NOT NULL,
	"frags" integer NOT NULL,
	"damage_dealt" bigint NOT NULL,
	"damage_received" bigint NOT NULL,
	"xp" bigint NOT NULL,
	"battle_avg_xp" integer NOT NULL,
	"spotted" integer NOT NULL,
	"capture_points" integer NOT NULL,
	"dropped_capture_points" integer NOT NULL,
	"hits" integer NOT NULL,
	"shots" integer NOT NULL,
	"hits_percents" real NOT NULL,
	"global_rating" integer NOT NULL,
	"wtr" integer,
	"clan_id" bigint
);
--> statement-breakpoint
CREATE TABLE "eu_players" (
	"id" serial PRIMARY KEY NOT NULL,
	"account_id" bigint NOT NULL,
	"nickname" text NOT NULL,
	"created_at" timestamp with time zone,
	"last_battle_at" timestamp with time zone,
	"clan_id" bigint,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"wn7" real,
	"wn8" real,
	"wnx" real,
	"wn7_30d" real,
	"wn8_30d" real,
	"wnx_30d" real,
	"battles" integer,
	"battles_30d" integer,
	"null_count" integer DEFAULT 0 NOT NULL,
	"soft_deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "eu_tank_snapshots" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"tank_id" integer NOT NULL,
	"taken_at" timestamp with time zone DEFAULT now() NOT NULL,
	"battles" integer NOT NULL,
	"wins" integer NOT NULL,
	"damage_dealt" bigint NOT NULL,
	"spotted" integer NOT NULL,
	"frags" integer NOT NULL,
	"dropped_capture_points" integer NOT NULL,
	"radio_assisted_damage" bigint NOT NULL,
	"track_assisted_damage" bigint NOT NULL,
	"xp" bigint,
	"mark_of_mastery" integer
);
--> statement-breakpoint
CREATE TABLE "eu_top_clans" (
	"metric" text NOT NULL,
	"rank" integer NOT NULL,
	"clan_id" bigint NOT NULL,
	"tag" text NOT NULL,
	"name" text NOT NULL,
	"color" text NOT NULL,
	"emblem" text,
	"members_count" integer NOT NULL,
	"rated_members_count" integer NOT NULL,
	"avg_wnx" numeric NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "eu_top_clans_metric_rank_pk" PRIMARY KEY("metric","rank")
);
--> statement-breakpoint
CREATE TABLE "eu_top_players" (
	"metric" text NOT NULL,
	"period" text NOT NULL,
	"rank" integer NOT NULL,
	"account_id" bigint NOT NULL,
	"nickname" text NOT NULL,
	"clan_tag" text,
	"clan_color" text,
	"battles" integer NOT NULL,
	"wnx" numeric NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "eu_top_players_metric_period_rank_pk" PRIMARY KEY("metric","period","rank")
);
--> statement-breakpoint
CREATE TABLE "eu_vehicles" (
	"tank_id" integer PRIMARY KEY NOT NULL,
	"tier" integer NOT NULL,
	"type" text NOT NULL,
	"nation" text NOT NULL,
	"name" text NOT NULL,
	"short_name" text NOT NULL,
	"tag" text NOT NULL,
	"is_premium" boolean NOT NULL,
	"is_wheeled" boolean NOT NULL,
	"is_gift" boolean NOT NULL,
	"small_icon" text,
	"contour_icon" text,
	"big_icon" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "na_clan_members" (
	"clan_id" bigint NOT NULL,
	"account_id" bigint NOT NULL,
	"name" text NOT NULL,
	"role" text NOT NULL,
	"role_localized" text NOT NULL,
	"role_rank" integer NOT NULL,
	"days_in_clan" integer NOT NULL,
	"last_battle_time" timestamp with time zone,
	"personal_rating" integer,
	"overall_battles" integer,
	"overall_wins_pct" real,
	"overall_damage_per_battle" real,
	"overall_exp_per_battle" real,
	"overall_frags_per_battle" real,
	"overall_battles_per_day" real,
	"d28_battles" integer,
	"d28_wins_pct" real,
	"d28_damage_per_battle" real,
	"d28_exp_per_battle" real,
	"d28_frags_per_battle" real,
	"d28_battles_per_day" real,
	"refreshed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "na_clan_members_clan_id_account_id_pk" PRIMARY KEY("clan_id","account_id")
);
--> statement-breakpoint
CREATE TABLE "na_clan_recent_events" (
	"clan_id" bigint NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"type" text NOT NULL,
	"account_id" bigint NOT NULL,
	"account_name" text NOT NULL,
	"old_role" text,
	"new_role" text,
	"old_rank" integer,
	"new_rank" integer,
	CONSTRAINT "na_clan_recent_events_clan_id_created_at_type_account_id_pk" PRIMARY KEY("clan_id","created_at","type","account_id")
);
--> statement-breakpoint
CREATE TABLE "na_clan_refresh_queue" (
	"clan_id" bigint PRIMARY KEY NOT NULL,
	"queued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "na_clans" (
	"id" bigint PRIMARY KEY NOT NULL,
	"tag" text NOT NULL,
	"tag_lower" text NOT NULL,
	"name" text NOT NULL,
	"color" text NOT NULL,
	"emblem" text NOT NULL,
	"motto" text NOT NULL,
	"description_html" text NOT NULL,
	"members_count" integer NOT NULL,
	"leader_id" bigint NOT NULL,
	"leader_name" text NOT NULL,
	"creator_id" bigint NOT NULL,
	"creator_name" text NOT NULL,
	"created_at_wg" timestamp with time zone NOT NULL,
	"is_disbanded" boolean DEFAULT false NOT NULL,
	"languages" text[] DEFAULT '{}' NOT NULL,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_refreshed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "na_player_clan_history" (
	"id" serial PRIMARY KEY NOT NULL,
	"account_id" bigint NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"data" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "na_player_refresh_queue" (
	"account_id" bigint PRIMARY KEY NOT NULL,
	"queued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "na_player_snapshots" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"taken_at" timestamp with time zone DEFAULT now() NOT NULL,
	"battles" integer NOT NULL,
	"wins" integer NOT NULL,
	"losses" integer NOT NULL,
	"draws" integer NOT NULL,
	"survived_battles" integer NOT NULL,
	"frags" integer NOT NULL,
	"damage_dealt" bigint NOT NULL,
	"damage_received" bigint NOT NULL,
	"xp" bigint NOT NULL,
	"battle_avg_xp" integer NOT NULL,
	"spotted" integer NOT NULL,
	"capture_points" integer NOT NULL,
	"dropped_capture_points" integer NOT NULL,
	"hits" integer NOT NULL,
	"shots" integer NOT NULL,
	"hits_percents" real NOT NULL,
	"global_rating" integer NOT NULL,
	"wtr" integer,
	"clan_id" bigint
);
--> statement-breakpoint
CREATE TABLE "na_players" (
	"id" serial PRIMARY KEY NOT NULL,
	"account_id" bigint NOT NULL,
	"nickname" text NOT NULL,
	"created_at" timestamp with time zone,
	"last_battle_at" timestamp with time zone,
	"clan_id" bigint,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"wn7" real,
	"wn8" real,
	"wnx" real,
	"wn7_30d" real,
	"wn8_30d" real,
	"wnx_30d" real,
	"battles" integer,
	"battles_30d" integer,
	"null_count" integer DEFAULT 0 NOT NULL,
	"soft_deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "na_tank_snapshots" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"tank_id" integer NOT NULL,
	"taken_at" timestamp with time zone DEFAULT now() NOT NULL,
	"battles" integer NOT NULL,
	"wins" integer NOT NULL,
	"damage_dealt" bigint NOT NULL,
	"spotted" integer NOT NULL,
	"frags" integer NOT NULL,
	"dropped_capture_points" integer NOT NULL,
	"radio_assisted_damage" bigint NOT NULL,
	"track_assisted_damage" bigint NOT NULL,
	"xp" bigint,
	"mark_of_mastery" integer
);
--> statement-breakpoint
CREATE TABLE "na_top_clans" (
	"metric" text NOT NULL,
	"rank" integer NOT NULL,
	"clan_id" bigint NOT NULL,
	"tag" text NOT NULL,
	"name" text NOT NULL,
	"color" text NOT NULL,
	"emblem" text,
	"members_count" integer NOT NULL,
	"rated_members_count" integer NOT NULL,
	"avg_wnx" numeric NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "na_top_clans_metric_rank_pk" PRIMARY KEY("metric","rank")
);
--> statement-breakpoint
CREATE TABLE "na_top_players" (
	"metric" text NOT NULL,
	"period" text NOT NULL,
	"rank" integer NOT NULL,
	"account_id" bigint NOT NULL,
	"nickname" text NOT NULL,
	"clan_tag" text,
	"clan_color" text,
	"battles" integer NOT NULL,
	"wnx" numeric NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "na_top_players_metric_period_rank_pk" PRIMARY KEY("metric","period","rank")
);
--> statement-breakpoint
CREATE TABLE "na_vehicles" (
	"tank_id" integer PRIMARY KEY NOT NULL,
	"tier" integer NOT NULL,
	"type" text NOT NULL,
	"nation" text NOT NULL,
	"name" text NOT NULL,
	"short_name" text NOT NULL,
	"tag" text NOT NULL,
	"is_premium" boolean NOT NULL,
	"is_wheeled" boolean NOT NULL,
	"is_gift" boolean NOT NULL,
	"small_icon" text,
	"contour_icon" text,
	"big_icon" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "asia_player_snapshots" ADD CONSTRAINT "asia_player_snapshots_player_id_asia_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."asia_players"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asia_tank_snapshots" ADD CONSTRAINT "asia_tank_snapshots_player_id_asia_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."asia_players"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eu_player_snapshots" ADD CONSTRAINT "eu_player_snapshots_player_id_eu_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."eu_players"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eu_tank_snapshots" ADD CONSTRAINT "eu_tank_snapshots_player_id_eu_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."eu_players"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "na_player_snapshots" ADD CONSTRAINT "na_player_snapshots_player_id_na_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."na_players"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "na_tank_snapshots" ADD CONSTRAINT "na_tank_snapshots_player_id_na_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."na_players"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "asia_clan_recent_events_clan_created_idx" ON "asia_clan_recent_events" USING btree ("clan_id","created_at");--> statement-breakpoint
CREATE INDEX "asia_clan_refresh_queue_priority_queued_at_idx" ON "asia_clan_refresh_queue" USING btree ("priority","queued_at");--> statement-breakpoint
CREATE UNIQUE INDEX "asia_clans_tag_lower_idx" ON "asia_clans" USING btree ("tag_lower");--> statement-breakpoint
CREATE INDEX "asia_clans_last_refreshed_at_idx" ON "asia_clans" USING btree ("last_refreshed_at");--> statement-breakpoint
CREATE UNIQUE INDEX "asia_player_clan_history_account_id_idx" ON "asia_player_clan_history" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "asia_player_refresh_queue_priority_queued_at_idx" ON "asia_player_refresh_queue" USING btree ("priority","queued_at");--> statement-breakpoint
CREATE INDEX "asia_snapshots_player_id_taken_at_idx" ON "asia_player_snapshots" USING btree ("player_id","taken_at");--> statement-breakpoint
CREATE UNIQUE INDEX "asia_snapshots_player_id_battles_unique_idx" ON "asia_player_snapshots" USING btree ("player_id","battles");--> statement-breakpoint
CREATE INDEX "asia_snapshots_clan_id_idx" ON "asia_player_snapshots" USING btree ("clan_id");--> statement-breakpoint
CREATE UNIQUE INDEX "asia_players_account_id_idx" ON "asia_players" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "asia_players_lower_nickname_idx" ON "asia_players" USING btree (LOWER("nickname"));--> statement-breakpoint
CREATE INDEX "asia_tank_snapshots_player_taken_idx" ON "asia_tank_snapshots" USING btree ("player_id","taken_at");--> statement-breakpoint
CREATE UNIQUE INDEX "asia_tank_snapshots_player_tank_battles_unique_idx" ON "asia_tank_snapshots" USING btree ("player_id","tank_id","battles");--> statement-breakpoint
CREATE INDEX "eu_clan_recent_events_clan_created_idx" ON "eu_clan_recent_events" USING btree ("clan_id","created_at");--> statement-breakpoint
CREATE INDEX "eu_clan_refresh_queue_priority_queued_at_idx" ON "eu_clan_refresh_queue" USING btree ("priority","queued_at");--> statement-breakpoint
CREATE UNIQUE INDEX "eu_clans_tag_lower_idx" ON "eu_clans" USING btree ("tag_lower");--> statement-breakpoint
CREATE INDEX "eu_clans_last_refreshed_at_idx" ON "eu_clans" USING btree ("last_refreshed_at");--> statement-breakpoint
CREATE UNIQUE INDEX "eu_player_clan_history_account_id_idx" ON "eu_player_clan_history" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "eu_player_refresh_queue_priority_queued_at_idx" ON "eu_player_refresh_queue" USING btree ("priority","queued_at");--> statement-breakpoint
CREATE INDEX "eu_snapshots_player_id_taken_at_idx" ON "eu_player_snapshots" USING btree ("player_id","taken_at");--> statement-breakpoint
CREATE UNIQUE INDEX "eu_snapshots_player_id_battles_unique_idx" ON "eu_player_snapshots" USING btree ("player_id","battles");--> statement-breakpoint
CREATE INDEX "eu_snapshots_clan_id_idx" ON "eu_player_snapshots" USING btree ("clan_id");--> statement-breakpoint
CREATE UNIQUE INDEX "eu_players_account_id_idx" ON "eu_players" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "eu_players_lower_nickname_idx" ON "eu_players" USING btree (LOWER("nickname"));--> statement-breakpoint
CREATE INDEX "eu_tank_snapshots_player_taken_idx" ON "eu_tank_snapshots" USING btree ("player_id","taken_at");--> statement-breakpoint
CREATE UNIQUE INDEX "eu_tank_snapshots_player_tank_battles_unique_idx" ON "eu_tank_snapshots" USING btree ("player_id","tank_id","battles");--> statement-breakpoint
CREATE INDEX "na_clan_recent_events_clan_created_idx" ON "na_clan_recent_events" USING btree ("clan_id","created_at");--> statement-breakpoint
CREATE INDEX "na_clan_refresh_queue_priority_queued_at_idx" ON "na_clan_refresh_queue" USING btree ("priority","queued_at");--> statement-breakpoint
CREATE UNIQUE INDEX "na_clans_tag_lower_idx" ON "na_clans" USING btree ("tag_lower");--> statement-breakpoint
CREATE INDEX "na_clans_last_refreshed_at_idx" ON "na_clans" USING btree ("last_refreshed_at");--> statement-breakpoint
CREATE UNIQUE INDEX "na_player_clan_history_account_id_idx" ON "na_player_clan_history" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "na_player_refresh_queue_priority_queued_at_idx" ON "na_player_refresh_queue" USING btree ("priority","queued_at");--> statement-breakpoint
CREATE INDEX "na_snapshots_player_id_taken_at_idx" ON "na_player_snapshots" USING btree ("player_id","taken_at");--> statement-breakpoint
CREATE UNIQUE INDEX "na_snapshots_player_id_battles_unique_idx" ON "na_player_snapshots" USING btree ("player_id","battles");--> statement-breakpoint
CREATE INDEX "na_snapshots_clan_id_idx" ON "na_player_snapshots" USING btree ("clan_id");--> statement-breakpoint
CREATE UNIQUE INDEX "na_players_account_id_idx" ON "na_players" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "na_players_lower_nickname_idx" ON "na_players" USING btree (LOWER("nickname"));--> statement-breakpoint
CREATE INDEX "na_tank_snapshots_player_taken_idx" ON "na_tank_snapshots" USING btree ("player_id","taken_at");--> statement-breakpoint
CREATE UNIQUE INDEX "na_tank_snapshots_player_tank_battles_unique_idx" ON "na_tank_snapshots" USING btree ("player_id","tank_id","battles");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "eu_snapshots_latest_membership_idx" ON "eu_player_snapshots" USING btree ("player_id","taken_at" DESC,"id" DESC) INCLUDE ("clan_id","battles") WHERE "clan_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "na_snapshots_latest_membership_idx" ON "na_player_snapshots" USING btree ("player_id","taken_at" DESC,"id" DESC) INCLUDE ("clan_id","battles") WHERE "clan_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "asia_snapshots_latest_membership_idx" ON "asia_player_snapshots" USING btree ("player_id","taken_at" DESC,"id" DESC) INCLUDE ("clan_id","battles") WHERE "clan_id" IS NOT NULL;
