// Generates `src/locales/generated/`: one module per locale importing every
// translation file that locale carries, plus an index exposing the namespace
// list and a per-locale loader.
//
// The dictionaries are bundled rather than read from disk at runtime. The
// server build is `output: "standalone"`, which ships only what the tracer sees,
// so a `fs.readFile` of `src/locales` would be one more asset to remember to
// copy next to `server.js` and would fail silently in production the day someone
// forgot. A generated static import cannot be forgotten: it either compiles or
// it does not.
//
// English is the source of truth for the namespace list. The other locales are
// written by CI from it, so a locale that is behind simply imports fewer files
// and falls back to English key by key at runtime.
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_LOCALE, LOCALES } from "../src/lib/translations";

const webRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const localesRoot = join(webRoot, "src", "locales");
const outDir = join(localesRoot, "generated");

/** Every `*.json` under `dir`, as namespace paths (`layout/footer`). */
function namespacesIn(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  const walk = (current: string) => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith(".json")) {
        out.push(relative(dir, full).split(sep).join("/").replace(/\.json$/, ""));
      }
    }
  };
  walk(dir);
  return out.sort();
}


const namespaces = namespacesIn(join(localesRoot, DEFAULT_LOCALE));

mkdirSync(outDir, { recursive: true });
// A locale removed from the enum must not leave its module behind: the loader
// map would still be regenerated without it, but the stale file would keep
// importing translation files nothing else references.
for (const entry of readdirSync(outDir)) rmSync(join(outDir, entry));

const HEADER = `// Generated by scripts/generate-locales.ts (postinstall/predev/prebuild).
// Do not edit.`;

for (const locale of LOCALES) {
  // Only what this locale actually carries. A namespace it is missing resolves
  // through the English fallback rather than breaking the build.
  const carried = namespaces.filter((namespace) =>
    existsSync(join(localesRoot, locale, `${namespace}.json`)),
  );
  // One merged file per locale rather than one import per namespace.
  //
  // The shape the app sees is identical: `Dictionaries` is
  // `Partial<Record<Namespace, TranslationDictionary>>`, so the literal type of
  // each file was inferred and then immediately widened away. Nothing ever read
  // it, and computing it 12,240 times (340 namespaces x 36 locales) is what
  // took the build's TypeScript pass to 2.66 GB against its 1536 MB heap, where
  // it died with "Ineffective mark-compacts near heap limit" AFTER compiling
  // successfully. This leaves 36 JSON modules to type instead.
  //
  // Nothing is lost to the bundler either: the dictionaries object references
  // every namespace, so none of them was tree-shakeable before. A locale is
  // loaded whole (`loadDictionaries`), and the namespaces that must not cross
  // the wire are stripped at runtime in `components/document`, not here.
  const merged: Record<string, unknown> = {};
  for (const namespace of carried) {
    merged[namespace] = JSON.parse(
      readFileSync(join(localesRoot, locale, `${namespace}.json`), "utf-8"),
    );
  }
  writeFileSync(
    join(outDir, `${locale}.json`),
    `${JSON.stringify(merged, null, 2)}\n`,
  );

  writeFileSync(
    join(outDir, `${locale}.ts`),
    `${HEADER}
import type { Dictionaries } from ".";
import dictionaries from "./${locale}.json";

export default dictionaries as Dictionaries;
`,
  );
}

const namespaceUnion = namespaces.length
  ? namespaces.map((namespace) => `\n  | ${JSON.stringify(namespace)}`).join("")
  : " never";

const loaders = LOCALES.map(
  (locale) => `  ${JSON.stringify(locale)}: () => import("./${locale}"),`,
).join("\n");

writeFileSync(
  join(outDir, "index.ts"),
  `${HEADER}
import type { TranslationDictionary } from "@onruntime/translations";
import type { Locale } from "@/lib/translations";

/** Every translation file the English source declares, by path from
 * \`src/locales/<locale>/\`. Passing anything else to \`getTranslation\` or
 * \`useTranslation\` is a compile error rather than a key echoed at a reader. */
export type Namespace =${namespaceUnion};

export const NAMESPACES: readonly Namespace[] = [
${namespaces.map((namespace) => `  ${JSON.stringify(namespace)},`).join("\n")}
];

export type Dictionaries = Partial<Record<Namespace, TranslationDictionary>>;

const LOADERS: Record<Locale, () => Promise<{ default: Dictionaries }>> = {
${loaders}
};

/** Everything one locale carries, as one chunk. Awaited once per locale per
 * process by \`lib/translations.server\`, which caches it. */
export function loadDictionaries(locale: Locale): Promise<Dictionaries> {
  return LOADERS[locale]().then((module) => module.default);
}
`,
);

console.log(
  `[locales] ${namespaces.length} namespace(s) x ${LOCALES.length} locale(s) -> ${relative(webRoot, outDir)}`,
);
