// Generates `src/proxy-routes.generated.ts`: the app-router path patterns of
// every public page, split by whether they carry a `[region]` segment.
//
// `proxy.ts` uses the two lists to answer one question without hardcoding a
// thing: "does this region-less URL match a real page, and would it match one
// if a region were prepended?" That is exactly the case of `/players/Straik`,
// which has no route of its own (player and clan pages live only under
// `/[region]`) while `/eu/players/Straik` does. Deriving it from the filesystem
// means a new section, or a new region-less shortcut, changes the proxy's
// behaviour by existing, with no list to keep in sync.
import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const appRoot = join(webRoot, "src", "app");
const outFile = join(webRoot, "src", "proxy-routes.generated.ts");

const REGION_SEGMENT = "[region]";

function filesNamed(dir: string, name: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...filesNamed(full, name));
    else if (entry.name === name) out.push(full);
  }
  return out;
}

const urlSegments = (file: string): string[] =>
  relative(appRoot, dirname(file))
    .split(sep)
    // Route groups (`(site)`) are organisational only: they never appear in a URL.
    .filter((s) => s && !s.startsWith("("));

const regional = new Set<string>();
const regionless = new Set<string>();
// Region-less route handlers (`/sitemap.xml`, `/maps/sitemap.xml`, `/llms.txt`).
// They are not pages and must never be region-redirected, yet a sibling
// `[slug]` pattern would happily match them, which is how `/maps/sitemap.xml`
// briefly became a redirect the day `/maps/[slug]` lost its region-less page.
const handlers = new Set<string>();

for (const file of filesNamed(appRoot, "route.ts").sort()) {
  const segments = urlSegments(file);
  // API routes are rewritten, never region-redirected; regional handlers are
  // already at their destination.
  if (segments[0] === "api" || segments.includes(REGION_SEGMENT)) continue;
  handlers.add(`/${segments.join("/")}`);
}

for (const file of filesNamed(appRoot, "page.tsx").sort()) {
  const segments = urlSegments(file);
  if (segments.includes(REGION_SEGMENT)) {
    // Compared against a region-less path, so drop the region segment itself.
    regional.add(`/${segments.filter((s) => s !== REGION_SEGMENT).join("/")}`);
  } else {
    regionless.add(`/${segments.join("/")}`);
  }
}

const list = (patterns: Set<string>): string =>
  [...patterns]
    .sort()
    .map((pattern) => `  ${JSON.stringify(pattern)},`)
    .join("\n");

const body = `// Generated by scripts/generate-page-routes.ts (postinstall/predev/prebuild).
// Do not edit.
//
// Page path patterns, with the \`[region]\` segment stripped from the regional
// ones so both lists are directly comparable to a region-less URL. See
// \`proxy.ts\`, which redirects a URL that only the regional list can serve.

/** Pages reachable without a region (\`/players\`, \`/tanks/[slug]\`). */
export const REGIONLESS_PAGES: readonly string[] = [
${list(regionless)}
];

/** Pages that exist under \`/[region]\`, region segment removed. */
export const REGIONAL_PAGES: readonly string[] = [
${list(regional)}
];

/** Region-less route handlers (sitemaps, text files). Never redirected: they
 * are not pages, and a sibling \`[slug]\` page pattern would otherwise match. */
export const REGIONLESS_HANDLERS: readonly string[] = [
${list(handlers)}
];
`;

writeFileSync(outFile, body);
console.log(
  `[page-routes] ${regionless.size} region-less + ${regional.size} regional page(s) → ${relative(webRoot, outFile)}`,
);
