// Generates `src/services/sdk/local-routes.generated.ts`: a filesystem-derived
// registry of every public API route handler that exports a GET, as lazy
// import thunks. `services/sdk/loopback.ts` uses it during `next build` to
// dispatch the SDK's calls to the in-process handlers of the commit being
// built, so statically prerendered pages get real data without depending on a
// running (or up-to-date) deployed API.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const apiRoot = join(webRoot, "src", "app", "api");
const outFile = join(
  webRoot,
  "src",
  "services",
  "sdk",
  "local-routes.generated.ts",
);

type Entry = { pattern: string; importPath: string };

function routeFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...routeFiles(full));
    else if (entry.name === "route.ts") out.push(full);
  }
  return out;
}

// Next router precedence at every segment position: static beats dynamic
// beats catch-all. The registry is emitted in that order, so the matcher's
// first hit is always the same route Next itself would pick.
function segmentRank(segment: string): number {
  if (segment.startsWith("[...") || segment.startsWith("[[...")) return 2;
  if (segment.startsWith("[")) return 1;
  return 0;
}

function byPrecedence(a: Entry, b: Entry): number {
  const as = a.pattern.split("/").filter(Boolean);
  const bs = b.pattern.split("/").filter(Boolean);
  const len = Math.max(as.length, bs.length);
  for (let i = 0; i < len; i++) {
    if (as[i] === undefined) return -1;
    if (bs[i] === undefined) return 1;
    const rank = segmentRank(as[i]) - segmentRank(bs[i]);
    if (rank !== 0) return rank;
    const alpha = as[i].localeCompare(bs[i]);
    if (alpha !== 0) return alpha;
  }
  return 0;
}

const entries: Entry[] = [];
for (const file of routeFiles(apiRoot).sort()) {
  const source = readFileSync(file, "utf8");
  if (
    !/export\s+(async\s+)?function\s+GET\b|export\s+const\s+GET\b|export\s*\{[^}]*\bGET\b/.test(
      source,
    )
  ) {
    continue;
  }
  // src/app/api/[region]/players/[nickname]/route.ts → /api/[region]/players/[nickname]
  const rel = relative(join(webRoot, "src", "app"), dirname(file))
    .split(sep)
    .join("/");
  entries.push({ pattern: `/${rel}`, importPath: `@/app/${rel}/route` });
}
entries.sort(byPrecedence);

const body = `// Generated by scripts/generate-local-routes.ts (prebuild/predev). Do not edit.
// Every public API route handler exporting a GET, keyed by its app-router
// path pattern. Consumed by \`services/sdk/loopback.ts\` to dispatch server-side
// SDK calls in-process (at build for prerender, and at runtime for SSR/ISR)
// instead of self-fetching the API over HTTP.

export type LocalRouteModule = {
  GET: (
    req: Request,
    ctx: { params: Promise<Record<string, string | string[]>> },
  ) => Response | Promise<Response>;
};

export const LOCAL_ROUTES: ReadonlyArray<{
  pattern: string;
  load: () => Promise<LocalRouteModule>;
}> = [
${entries
  .map(
    (e) =>
      `  { pattern: ${JSON.stringify(e.pattern)}, load: () => import(${JSON.stringify(e.importPath)}) as unknown as Promise<LocalRouteModule> },`,
  )
  .join("\n")}
];
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body);
console.log(
  `[local-routes] ${entries.length} GET route(s) → ${relative(webRoot, outFile)}`,
);
