import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const ENV_TS = resolve(ROOT, "env.ts");
const ENV_LOCAL = resolve(ROOT, ".env.local");

function timestamp(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`;
}

let backupRelPath: string | null = null;
if (existsSync(ENV_LOCAL)) {
  const backupPath = `${ENV_LOCAL}.${timestamp()}.bak`;
  renameSync(ENV_LOCAL, backupPath);
  backupRelPath = basename(backupPath);
}

const source = readFileSync(ENV_TS, "utf8");

function extractKeys(label: "server" | "client"): string[] {
  // server: { ... } and client: { ... } blocks are flat (no nested braces),
  // so [^{}] is enough to bound them without leaking into runtimeEnv.
  const re = new RegExp(`${label}\\s*:\\s*\\{([^{}]*)\\}`);
  const match = source.match(re);
  if (!match) return [];
  return Array.from(match[1].matchAll(/^\s*([A-Z_][A-Z0-9_]*)\s*:/gm)).map(
    (m) => m[1],
  );
}

const serverKeys = extractKeys("server");
const clientKeys = extractKeys("client");

if (serverKeys.length === 0 && clientKeys.length === 0) {
  console.error(
    "\x1b[31m✗ Could not parse any env keys from env.ts. Has its structure changed?\x1b[0m",
  );
  process.exit(1);
}

const lines: string[] = [
  "# Generated by `pnpm env:init`. Fill in the values below.",
];
if (serverKeys.length > 0) {
  lines.push("", "# Server");
  for (const key of serverKeys) lines.push(`${key}=`);
}
if (clientKeys.length > 0) {
  lines.push("", "# Client");
  for (const key of clientKeys) lines.push(`${key}=`);
}
lines.push("");

writeFileSync(ENV_LOCAL, lines.join("\n"), { flag: "wx" });

console.log(
  `\x1b[32m✓ .env.local created with ${serverKeys.length + clientKeys.length} keys.\x1b[0m`,
);
if (backupRelPath) {
  console.log(
    `\x1b[2m  Previous file backed up to ${backupRelPath}\x1b[0m`,
  );
}
