import { parse } from "node-html-parser";
import APP from "@/constants/app";
import { stripSiteName } from "@/lib/metadata";

/**
 * Markdown rendering of a sitemap, the XML counterpart of the HTML page
 * converter in `app/api/md`.
 *
 * It invents no structure of its own: a sitemap index becomes a list of links
 * to each sub-sitemap's own `.md`, a urlset becomes a list of links to each
 * page's `.md`. Follow one and you get the next, exactly as a crawler walks the
 * XML. So `/sitemap.md` is the readable twin of `/sitemap.xml` and nothing more,
 * which is why a new kind of entity needs no code here: it gets a sub-sitemap
 * because crawlers need one, and that sub-sitemap is readable for free.
 */

/** `/sitemap`, `/maps/sitemap`, `/eu/players/sitemap-3`. */
export function isSitemapPath(path: string): boolean {
  return /(?:^|\/)sitemap(?:-\d+)?$/.test(path);
}

/**
 * Above this many URLs the list is rendered from paths alone. Below it every
 * page is fetched for its `<title>`, which is what makes the document readable.
 * The entity sitemaps run to 25k URLs, so this is the line between "a catalogue
 * a reader can use" and "a crawl".
 */
const TITLED = 200;

const CONCURRENCY = 10;

async function mapWithLimit<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>,
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      for (let i = next++; i < items.length; i = next++) {
        results[i] = await fn(items[i]);
      }
    }),
  );
  return results;
}

/** `<loc>` values, by regex rather than an XML parser: this is our own output,
 * generated by `generateSitemapXml`, not third-party markup. */
function locations(xml: string): string[] {
  return [...xml.matchAll(/<loc>([^<]*)<\/loc>/g)].map((m) =>
    m[1].replace(APP.URL, ""),
  );
}

/** A page's Markdown twin, mirroring `toMarkdownHref` in the page converter. */
function asMarkdown(path: string): string {
  return path === "" || path === "/" ? "/index.md" : `${path}.md`;
}

async function fetchTitle(origin: string, path: string): Promise<string | null> {
  try {
    const response = await fetch(`${origin}${path}`, {
      headers: { Accept: "text/html" },
      cache: "no-store",
      // Bounded: a page slow enough to blow this is better shown as its path
      // than allowed to hold up the whole document.
      signal: AbortSignal.timeout(15_000),
    });
    if (!response.ok) return null;
    const title = parse(await response.text())
      .querySelector("title")
      ?.text?.trim();
    return title ? stripSiteName(title) : null;
  } catch {
    return null;
  }
}

/**
 * Each page's own `<title>`, minus the site-name suffix `constructMetadata`
 * appends. Null where the page will not answer, which leaves the path as the
 * label rather than inventing one.
 *
 * The second pass is not superstition: a miss means the page was cold, and the
 * attempt that timed out is the one that paid for its render. Retrying once the
 * first pass is done finds it warm and the queue idle, which is the difference
 * between a document missing its heaviest pages and a complete one.
 */
async function titlesOf(
  origin: string,
  paths: string[],
): Promise<(string | null)[]> {
  const titles = await mapWithLimit(paths, CONCURRENCY, (path) =>
    fetchTitle(origin, path),
  );
  const missed = paths.filter((_, i) => titles[i] === null);
  if (missed.length === 0) return titles;

  const retried = await mapWithLimit(missed, CONCURRENCY, (path) =>
    fetchTitle(origin, path),
  );
  let next = 0;
  return titles.map((title) => title ?? retried[next++]);
}

export async function sitemapToMarkdown(
  xml: string,
  origin: string,
  source: string,
): Promise<string> {
  const paths = locations(xml);
  // A sitemap index points at sitemaps, so its entries link to their own
  // Markdown rather than to a page.
  const isIndex = xml.includes("<sitemapindex");

  let lines: string[];
  if (isIndex) {
    lines = paths.map((path) => {
      const twin = path.replace(/\.xml$/, ".md");
      return `- [${path}](${twin})`;
    });
  } else {
    const titles =
      paths.length <= TITLED
        ? await titlesOf(origin, paths)
        : paths.map(() => null);
    lines = paths.map(
      (path, i) => `- [${titles[i] ?? path}](${asMarkdown(path)})`,
    );
  }

  return [
    `# ${source}`,
    "",
    isIndex
      ? `${paths.length} sitemaps. Each links to its own Markdown rendering.`
      : `${paths.length} URLs. Append \`.md\` to any page on this site to read it as Markdown.`,
    "",
    ...lines,
    "",
  ].join("\n");
}
