-- Global per-tank in-game specifications (top config), parsed from the
-- wot-src game client mirror. Region-agnostic (WG balances vehicles the same
-- everywhere), so a single table keyed by tank_id serves all regions.
CREATE TABLE IF NOT EXISTS "tank_specs" (
  "tank_id" bigint PRIMARY KEY NOT NULL,
  "damage" real,
  "module_damage" real,
  "splash_radius" real,
  "reload" real,
  "rof" real,
  "intra_clip_reload" real,
  "dpm" real,
  "penetration" real,
  "caliber" real,
  "shell_velocity" real,
  "accuracy" real,
  "aim_time" real,
  "disp_moving" real,
  "disp_tank_traverse" real,
  "disp_turret_traverse" real,
  "disp_after_shot" real,
  "disp_while_damaged" real,
  "gun_arc" real,
  "depression" real,
  "elevation" real,
  "speed_forward" real,
  "speed_backward" real,
  "hull_traverse" real,
  "turret_traverse" real,
  "engine_power" real,
  "power_weight" real,
  "terrain_hard" real,
  "terrain_medium" real,
  "terrain_soft" real,
  "health" real,
  "engine_health" real,
  "engine_fire_chance" real,
  "hull_armor_front" real,
  "turret_armor_front" real,
  "track_armor" real,
  "track_health" real,
  "track_repair_time" real,
  "ammo_rack_health" real,
  "weight" real,
  "view_range" real,
  "radio_range" real,
  "camo_still" real,
  "camo_moving" real,
  "camo_still_firing" real,
  "camo_moving_firing" real,
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
